### ISSUE TITLE
can't install from pipy

### ISSUE THREAD

**Issue by jab3z** [wooyek/django-tasker#3]
Hello,

While trying to do pip install on python 2.7 env and pip 10.0.1 i get the following error:

Collecting django-tasker
  Using cached https://files.pythonhosted.org/packages/78/b2/2342aad372370163666e5f49960881bb2c6cd0b7d06ac8297397399be723/django-tasker-0.2.57.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rw/yjlkzw292p19hsmzk4wbfrpw0000gn/T/pip-install-xkD36v/django-tasker/setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rw/yjlkzw292p19hsmzk4wbfrpw0000gn/T/pip-install-xkD36v/django-tasker/

**Comment by wooyek** [comment]
Should work now. Sorry about that.

**Comment by jab3z** [comment]
Yeah, saw it also :(

**Comment by wooyek** [comment]
If you're willing to spare some time you can try implement py27 support. The bulk of incompatibilities lay in the use of system attributes. Take a look at [decorators](https://github.com/wooyek/django-tasker/blob/develop/django_tasker/decoration.py) and [get_target_name](https://github.com/wooyek/django-tasker/blob/develop/django_tasker/models.py#L252).

**Comment by jab3z** [comment]
No, sorry. I just needed a quick db queue for a small project, already found one :)
